"""
Router: /agente-ia/chat — Chat with Gemini using LangChain + Supabase SQL.

SECURITY:
- user_id is extracted from the JWT via CurrentUser, NEVER from client input.
- All SQL queries are generated by Gemini and executed via the read-only RPC.
- Only SELECT queries are allowed (enforced at the RPC level).
"""

from fastapi import APIRouter
from pydantic import BaseModel

from app.api.deps import CurrentUser
from DADOS_PARA_LANGCHAIN.services.chat_service import chat_with_gemini

router = APIRouter(
    prefix="/agente-ia",
    tags=["Agente de IA - Chat Gemini"],
)


class ChatRequest(BaseModel):
    """Request model for the chat endpoint."""
    pergunta: str


class ChatResponse(BaseModel):
    """Response model for the chat endpoint."""
    resposta: str


@router.post(
    "/chat",
    response_model=ChatResponse,
    summary="Chat com Gemini via LangChain",
    description=(
        "Envia uma pergunta em linguagem natural. O sistema gera uma query SQL "
        "com base na estrutura das tabelas do usuário, executa a consulta no "
        "Supabase e retorna uma resposta em texto gerada pelo Gemini."
    ),
)
async def chat(
    current_user: CurrentUser,
    body: ChatRequest,
) -> ChatResponse:
    """
    Process a natural language question using LangChain + Gemini.

    1. Extracts user_id from the JWT (never from client input).
    2. Fetches the schema context for the user's tables.
    3. Gemini generates a SQL query from the question + schema.
    4. Executes the SQL via the read-only Supabase RPC.
    5. Gemini generates a natural language response from the results.
    """
    user_id = current_user.get("sub")
    if not user_id:
        return ChatResponse(resposta="Usuário não autenticado.")

    resposta = await chat_with_gemini(user_id, body.pergunta)
    return ChatResponse(resposta=resposta)